db:
  db_name: "honey_db" # 数据库名
  host: "82.157.155.26" # 数据库地址  
  port: 3306  # 数据库端口
  user: "ayp" # 数据库用户名
  password: "801026qwe" # 数据库密码
  maxIdleConns: 10 # 最大空闲连接数
  maxOpenConns: 100 # 最大连接数
  connMaxLifetime: 300 # 连接最大生命周期，单位秒

logger:
  format: text # 日志格式 可选值: text, json
  appName: honey_server # 应用名称
  level: info # 日志级别 可选值: debug, info, warn, error, fatal, panic