db:
  db_name: "honey_db" # 数据库名
  host: "82.157.155.26" # 数据库地址  
  port: 3306  # 数据库端口
  user: "ayp" # 数据库用户名
  password: "801026qwe" # 数据库密码

logger:
  format: text # 日志格式 可选值: text, json
  appName: honey_server # 应用名称
  level: info # 日志级别 可选值: debug, info, warn, error, fatal, panic